### ISSUE TITLE
can't connect on flatpak version

### ISSUE THREAD

**Issue by shmu26** [flathub/io.github.prateekmedia.appimagepool#3]
I installed version 4.4.0
from here
https://flathub.org/apps/details/io.github.prateekmedia.appimagepool
installed on MX Linux 21 KDE (based on Debian Bullseye)
when I open the app it complains "can't connect you need an internet connection to use appimage pool"

**Comment by prateekmedia** [comment]
The error tells the reason, your internet is weak or is not their at all.

**Comment by shmu26** [comment]
That doesn't seem to be the case, as this webpage opened for me quickly, and I ran the app just a second later, and got the same error. It is reproducible. 
Maybe there are some permissions that need to be set?

**Comment by prateekmedia** [comment]
Closing as this should be fixed now!
