### ISSUE TITLE
Can't change download path due to Zenity not present in GNOME runtime

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/io.github.prateekmedia.appimagepool#8]
The download path for applications can't be changed because it wants to use Zenity to bring up a file chooser.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/file_picker_linux.dart:98)
<asynchronous suspension>
#2      FilePickerLinux.getDirectoryPath (package:file_picker/src/file_picker_linux.dart:57)
<asynchronous suspension>
#3      PrefsDialog.build.<anonymous closure> (package:appimagepool/widgets/prefs_dialog.dart:121)
<asynchronous suspension>
```

Zenity was removed from the GNOME runtime, but it's present in the FreeDesktop.org runtime:

```
  ~ took 1m46s
❯ flatpak run --command=bash io.github.prateekmedia.appimagepool
[📦 io.github.prateekmedia.appimagepool ~]$ which zenity
which: no zenity in (/app/bin:/usr/bin)
[📦 io.github.prateekmedia.appimagepool ~]$ exit
exit

  ~ took 4s
❯ flatpak run --command=bash org.mozilla.firefox
[📦 org.mozilla.firefox ~]$ which zenity
/usr/bin/zenity
[📦 org.mozilla.firefox ~]$ 
```

GTK3 is present in the FreeDesktop.org runtime. Use of GTK does not necessarily mean the GNOME runtime is appropriate, because GTK != GNOME. I recommend migrating to the FreeDesktop.org runtime.

**Comment by HugLifeTiZ** [comment]
Okay, so after I switched this app to FD.O, I was able to get the file picker to come up, but it uses the portal, so the path it gives back is a fake one generated via the document portal. The textbox next to the chooser button is fake, so you can't type in a path manually.

Because zenity uses the portal, you can't even pick the default folder anymore; the path is abstracted by the portal and will thus be invalid on next run. This will need to be fixed upstream. If flutter-gtk is what uses zenity, it may need to be pushed up to them.

![Screenshot_2022-01-07_14-55-30](https://user-images.githubusercontent.com/4130673/148600194-32e0a2ae-2848-423c-82ac-98a469d7d30e.png)

**Comment by bilelmoussaoui** [comment]
The path will still be valid in the next run. Whatever you get access to through the portal is auto-mounted when you run your application

**Comment by HugLifeTiZ** [comment]
I actually just verified that's how it works, so I guess that means #9 does indeed fix this. Are there certain paths in the system where it doesn't work that way? I remember trying to do that in OBS Studio with a folder under `/run/user/1000` and it didn't work.

**Comment by HugLifeTiZ** [comment]
Well thanks to @bilelmoussaoui's guidance and the fact that #9 is now merged, I think that we can close this :)

**Comment by bilelmoussaoui** [comment]
There is an issue btw in the portal (xdg-desktop-portal) to provide a way to get the real path instead of the one the documents portal provides you. But that doesn't mean you can edit it manually as you won't have access to the newly modified file URI, you will have to go through the native dialog to request a new one.

**Comment by HugLifeTiZ** [comment]
That shouldn't affect the auto-mounts from portal folder selections though, right? I mean, with this, you don't even need to use flatseal to provide permissions to the folder you want AppImages to live in, since it auto-mounts. It's probably actually *better* that the textbox next to the button isn't editable, so that the abstracted path provided by the portal doesn't get messed up. I'm understanding the situation correctly here, right?

**Comment by bilelmoussaoui** [comment]
Yes the textbox shouldn't be editable
